"""phase3 techniques system

Revision ID: 48681c6c470b
Revises: 8d459e120387
Create Date: 2026-05-12 17:51:33.795422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48681c6c470b'
down_revision: Union[str, Sequence[str], None] = '8d459e120387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('techniques',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.Enum('FUNDAMENTAL', 'GUARD', 'PASS', 'SWEEP', 'SUBMISSION', 'ESCAPE', 'TAKEDOWN', 'TRANSITION', name='technique_category'), nullable=False),
    sa.Column('discipline', sa.Enum('BOTH', 'GI_ONLY', 'NO_GI_ONLY', name='technique_discipline'), nullable=False),
    sa.Column('belt_required', postgresql.ENUM('WHITE', 'BLUE', 'PURPLE', 'BROWN', 'BLACK', name='belt', create_type=False), nullable=False),
    sa.Column('stripes_required', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('prerequisite_technique_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_techniques_slug'), 'techniques', ['slug'], unique=True)
    op.create_table('user_techniques',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('LOCKED', 'UNLOCKED', 'ATTEMPTED', 'MASTERED', name='technique_status'), nullable=False),
    sa.Column('times_practiced', sa.Integer(), nullable=False),
    sa.Column('first_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mastered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['technique_id'], ['techniques.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'technique_id', name='uq_user_technique')
    )
    op.create_index(op.f('ix_user_techniques_technique_id'), 'user_techniques', ['technique_id'], unique=False)
    op.create_index(op.f('ix_user_techniques_user_id'), 'user_techniques', ['user_id'], unique=False)
    op.add_column(
        'training_sessions',
        sa.Column('technique_ids', postgresql.ARRAY(sa.Integer()), nullable=False, server_default='{}'),
    )
    op.alter_column('training_sessions', 'technique_ids', server_default=None)
    op.add_column('users', sa.Column('xp', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('users', 'xp', server_default=None)
    op.add_column(
        'users',
        sa.Column('stripes_earned_in_app', sa.Integer(), nullable=False, server_default='0'),
    )
    op.alter_column('users', 'stripes_earned_in_app', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stripes_earned_in_app')
    op.drop_column('users', 'xp')
    op.drop_column('training_sessions', 'technique_ids')
    op.drop_index(op.f('ix_user_techniques_user_id'), table_name='user_techniques')
    op.drop_index(op.f('ix_user_techniques_technique_id'), table_name='user_techniques')
    op.drop_table('user_techniques')
    op.drop_index(op.f('ix_techniques_slug'), table_name='techniques')
    op.drop_table('techniques')
    # ### end Alembic commands ###
