"""initial_users_table

Revision ID: 7889dfe14c4f
Revises: 
Create Date: 2026-05-10 19:35:11.691696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7889dfe14c4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('practices_gi', sa.Boolean(), nullable=False),
    sa.Column('gi_belt', sa.Enum('WHITE', 'BLUE', 'PURPLE', 'BROWN', 'BLACK', name='belt'), nullable=True),
    sa.Column('gi_stripes', sa.Integer(), nullable=False),
    sa.Column('practices_no_gi', sa.Boolean(), nullable=False),
    sa.Column('no_gi_belt', sa.Enum('WHITE', 'BLUE', 'PURPLE', 'BROWN', 'BLACK', name='belt'), nullable=True),
    sa.Column('no_gi_stripes', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
